// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVXNeGkrQDBh4205vCCo2jbLsvYRgoPVE',
    appId: '1:399621603010:web:50ac23985b8c76cdff055b',
    messagingSenderId: '399621603010',
    projectId: 'lastproject-6af51',
    authDomain: 'lastproject-6af51.firebaseapp.com',
    storageBucket: 'lastproject-6af51.appspot.com',
    measurementId: 'G-NG92BRMPR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeWUjEScqizXflmWXK5vNH5h9fal3yVnY',
    appId: '1:399621603010:android:b3aed152154d8e4dff055b',
    messagingSenderId: '399621603010',
    projectId: 'lastproject-6af51',
    storageBucket: 'lastproject-6af51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm0Eg8IgcpzD0eBRKyTi5Z8rz1j_qqW2o',
    appId: '1:399621603010:ios:c211f2f51a06873bff055b',
    messagingSenderId: '399621603010',
    projectId: 'lastproject-6af51',
    storageBucket: 'lastproject-6af51.appspot.com',
    iosClientId: '399621603010-rrloka8u5q9jvao51vqhcf93rnd38rvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.lastProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm0Eg8IgcpzD0eBRKyTi5Z8rz1j_qqW2o',
    appId: '1:399621603010:ios:c211f2f51a06873bff055b',
    messagingSenderId: '399621603010',
    projectId: 'lastproject-6af51',
    storageBucket: 'lastproject-6af51.appspot.com',
    iosClientId: '399621603010-rrloka8u5q9jvao51vqhcf93rnd38rvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.lastProject',
  );
}
